### ISSUE TITLE
🐛 : Edit profile picture button does not work

### ISSUE THREAD

**Issue by Aboud202** [langx/langx#747] opened 2024-05-23 21:46 UTC
Describe the bug:
I wanted to change profile picture from default to another, I tapped / Edit/, but nothing happened.

To Reproduce

Go to Profile section
Click on Edit button
Tap on "edit" button in the (Profile Picture")
section
Or tapping on (Add) in 
(Other pictures) Section 

https://github.com/langx/langx/assets/170677858/2dd3dace-8988-4ada-96e9-6f2bd35f3701

**Comment by xuelink** [comment] 2024-05-24 08:53
Duplicate of w/ #744

**Closed by xuelink** 2024-05-24 08:53 UTC
Labels: bug, duplicate
