### ISSUE TITLE
🚀 : Renaming "Name" to "Display Name"

### ISSUE THREAD

**Issue by binbang12** [langx/langx#776] opened 2024-06-09 19:25 UTC
*Idea*

When messaging with a lot of people, it can be really hard to keep a lot of names straight, even for those who are really good with names (I am not one of those people!). Therefore, I think being able to add custom "nicknames" for people would be a valuable feature.

*Benefits*

As mentioned above, it can be hard to keep track of names, therefore, a nickname of your choosing might be away to get around that problem. Take a user named Bob for example. You guys are both learning Spanish, so your chats consist of a lot of Spanish with some English mixed in to help each other out. Now let's say you have a lot of other people your messaging, each in a different language, or one of them is just a friend you found and your both speaking in your native tongue. You want to be able to quickly distinguish between what languages or what kind of conversations your having with different users. That's why nicknames would help. Instead of a person named Billy, you could nickname them Billy (Spanish), or Billy (Friend), or Billy (Economics), making it much easier to tell who you are really talking to.

*Implementation*

The nicknames would be implemented so that each was private and visible only to the person who assigned the nickname. The user who has been assigned the username would not be able to see it.

**Comment by xuelink** [comment] 2024-06-09 19:27
I think it's duplicate of #757

**Comment by binbang12** [comment] 2024-06-09 19:31
Hey Xue, I think you may have misunderstood? I meant you could assign custom names to people, not search up people by tags. Sorry if I'm wrong.

**Comment by xuelink** [comment] 2024-06-09 19:48
> Hey @xuelink , I think you may have misunderstood? I meant you could assign custom names to people, not search up people by tags. Sorry if I'm wrong.

I got what you mean thats why i updated my comment to `related` instead of `duplicate` :D

**Comment by xuelink** [comment] 2024-06-14 16:50
- [ ] Renaming `Name` to `Display Name` is going to close this issue.

**Closed** 2024-06-14 17:10 UTC
Labels: feature
